server:
  port: 8090
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: feedback
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: feedback
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    contexts: postgres

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: feedback
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: ru.pozdeev.feedbackservice.dto.event.CustomerEvent
  shedlock:
    defaults:
      lock-at-most-for: PT30S
      lock-at-least-for: PT10S

feedback:
  sent-survey-expiry-days: 7
  unsent-survey-expiry-days: 60
  kafka:
    producer:
      daily-metrics:
        enabled: true
        topic: daily-metrics.V1
        sending-timeout-sec: 5
    consumer:
      group-id: feedback
      customer-events:
        enabled: true
        topic: customer-events.V1
